[package]
name = "u25"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[dependencies]
#primitive-types = {version="0.10", default-features=false}
crunchy = {version="*", default-features=false}
