[package]
name = "rust"
version = "0.1.0"
edition = "2021"


[dependencies]
blake3 = { version = "1.3.3", features = ["rayon"] }
kangarootwelve_xkcp = "0.1.5"

[features]
k12 = []
pure = ["blake3/pure"]
threading = []
